package sluice_test

import (
	"os"
	"regexp"
	"strconv"
	"strings"
	"testing"
)

// Every performance figure the README quotes must exist in the consolidated
// measurements, within rounding.
//
// This test exists because the two drifted apart within an hour of the
// consolidated file being created. The README was written from one run of
// `consolidate.sh` and the file regenerated by the next, and nothing noticed:
// a README quoting 152 µs beside a table saying 139 µs, both produced by the
// same script on the same machine, neither wrong when it was written.
//
// Numbers in two places is how one of them goes stale. Since the brief asks
// the README to carry the comparisons — a pointer to a table is not a
// comparison a reader will follow — the duplication stays and this checks it.

// figure is one quoted number and the benchmark it must come from.
type figure struct {
	readme    string // as written in README.md
	benchmark string // the row in docs/benchmarks.md
	nanos     float64
}

// readmeFigures is the one list of quoted numbers both tests below check
// against — a second hand-maintained copy of it is how the two tests drift
// from each other the same way the README drifts from the table.
var readmeFigures = []figure{
	{"898 µs", "BenchmarkWebDBSluiceOneConn", 898_000},
	{"12.9 ms", "BenchmarkWebDBPgxOneConn", 12_900_000},
}

// The tolerance is loose on purpose. The consolidated table reports a median
// with a spread beside it, and the README rounds to two or three significant
// figures; what this catches is a figure that came from a different *run*, not
// one rounded differently.
const figureTolerance = 0.06

func TestREADMEFiguresMatchTheConsolidatedMeasurements(t *testing.T) {
	consolidated, err := os.ReadFile("docs/benchmarks.md")
	if err != nil {
		t.Skipf("no consolidated measurements: %v", err)
	}
	readme, err := os.ReadFile("README.md")
	if err != nil {
		t.Fatal(err)
	}

	medians := parseMedians(t, string(consolidated))
	if len(medians) < 10 {
		t.Fatalf("parsed %d medians from the consolidated file; the format changed", len(medians))
	}

	for _, f := range readmeFigures {
		t.Run(f.benchmark, func(t *testing.T) {
			if !strings.Contains(string(readme), f.readme) {
				t.Fatalf("the README no longer quotes %q; update this test with it", f.readme)
			}
			got, ok := medians[f.benchmark]
			if !ok {
				t.Fatalf("%s is not in the consolidated file", f.benchmark)
			}
			if drift := relative(f.nanos, got); drift > figureTolerance {
				t.Errorf("README says %s (%.0f ns), consolidated says %.0f ns — %.0f%% apart.\n"+
					"One of them is from an older run; regenerate the README figure from the table.",
					f.readme, f.nanos, got, 100*drift)
			}
		})
	}
}

func relative(a, b float64) float64 {
	if b == 0 {
		return 1
	}
	d := (a - b) / b
	if d < 0 {
		return -d
	}
	return d
}

var medianRow = regexp.MustCompile(`^\|\s*` + "`" + `(Benchmark\w+)` + "`" + `\s*\|\s*(\d+) ns\s*\|`)

func parseMedians(t *testing.T, doc string) map[string]float64 {
	t.Helper()
	out := map[string]float64{}
	for line := range strings.SplitSeq(doc, "\n") {
		m := medianRow.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		v, err := strconv.ParseFloat(m[2], 64)
		if err != nil {
			t.Fatalf("unparseable median in %q: %v", line, err)
		}
		out[m[1]] = v
	}
	return out
}

// A row whose spread is over the flag threshold must not be quoted in the
// README at all: run-to-run variation larger than the differences being read
// for makes the figure meaningless however carefully it was obtained.
func TestREADMEDoesNotQuoteUnstableRows(t *testing.T) {
	consolidated, err := os.ReadFile("docs/benchmarks.md")
	if err != nil {
		t.Skipf("no consolidated measurements: %v", err)
	}
	flagged := regexp.MustCompile(`^\|\s*` + "`" + `(Benchmark\w+)` + "`" + `.*\*\*\s*\|`)

	var unstable []string
	for line := range strings.SplitSeq(string(consolidated), "\n") {
		if m := flagged.FindStringSubmatch(line); m != nil {
			unstable = append(unstable, m[1])
		}
	}
	if len(unstable) == 0 {
		return
	}
	// Not a failure by itself — the flag is information. It fails only if one
	// of those rows is also a number the README asks a reader to believe —
	// any of them, drawn from the same readmeFigures list the test above
	// checks, so the two cannot drift apart.
	quoted := map[string]string{}
	for _, f := range readmeFigures {
		quoted[f.benchmark] = f.readme
	}
	readmeBytes, err := os.ReadFile("README.md")
	if err != nil {
		t.Fatal(err)
	}
	readme := string(readmeBytes)
	var offenders int
	for _, nm := range unstable {
		if fig, ok := quoted[nm]; ok && strings.Contains(readme, fig) {
			offenders++
			t.Errorf("%s has a spread over the flag threshold and the README quotes it as %s; "+
				"raise BENCHTIME and regenerate before publishing that number", nm, fig)
		}
	}
	if offenders == 0 {
		t.Logf("%d rows flagged as unstable, none of them quoted: %v", len(unstable), unstable)
	}
}
