// Code generated by sluicegen (format 1). DO NOT EDIT.

package entity

import (
	"fmt"
	"slices"

	"github.com/mlagarrigue/sluice/database/postgres"
)

// OrderPlan binds Order's fields to the columns of one result.
//
// Binding happens once per result rather than once per row, and it is where
// two mistakes are caught that would otherwise be silent: a column that moved
// (columns are matched by name, never by position) and a column whose type
// changed under the entity.
type OrderPlan struct {
	colID        int
	colTotal     int
	colLabel     int
	colActive    int
	colCreatedAt int
	colNote      int
}

// BindOrder resolves the columns Order needs in the result described
// by fields.
func BindOrder(fields []postgres.Field) (OrderPlan, error) {
	var p OrderPlan
	p.colID = -1
	p.colTotal = -1
	p.colLabel = -1
	p.colActive = -1
	p.colCreatedAt = -1
	p.colNote = -1
	for i, f := range fields {
		switch f.Name {
		case "id":
			if p.colID >= 0 {
				// Two columns of this name in one result — an ordinary join
				// does it. Last-wins binding would pick one silently, and
				// which one is a property of the SELECT's column order:
				// wrong data with no error. Alias one side instead.
				return p, fmt.Errorf("column %q appears more than once in the result and Order.ID cannot choose between them — alias one in the query", f.Name)
			}
			if f.TypeOID != postgres.OIDInt8 {
				return p, fmt.Errorf("column %q is OID %d, which Order.ID cannot hold", f.Name, f.TypeOID)
			}
			p.colID = i
		case "total_amount":
			if p.colTotal >= 0 {
				// Two columns of this name in one result — an ordinary join
				// does it. Last-wins binding would pick one silently, and
				// which one is a property of the SELECT's column order:
				// wrong data with no error. Alias one side instead.
				return p, fmt.Errorf("column %q appears more than once in the result and Order.Total cannot choose between them — alias one in the query", f.Name)
			}
			if f.TypeOID != postgres.OIDFloat8 {
				return p, fmt.Errorf("column %q is OID %d, which Order.Total cannot hold", f.Name, f.TypeOID)
			}
			p.colTotal = i
		case "label":
			if p.colLabel >= 0 {
				// Two columns of this name in one result — an ordinary join
				// does it. Last-wins binding would pick one silently, and
				// which one is a property of the SELECT's column order:
				// wrong data with no error. Alias one side instead.
				return p, fmt.Errorf("column %q appears more than once in the result and Order.Label cannot choose between them — alias one in the query", f.Name)
			}
			if f.TypeOID != postgres.OIDText && f.TypeOID != postgres.OIDVarchar && f.TypeOID != postgres.OIDBPChar && f.TypeOID != postgres.OIDName {
				return p, fmt.Errorf("column %q is OID %d, which Order.Label cannot hold", f.Name, f.TypeOID)
			}
			p.colLabel = i
		case "is_active":
			if p.colActive >= 0 {
				// Two columns of this name in one result — an ordinary join
				// does it. Last-wins binding would pick one silently, and
				// which one is a property of the SELECT's column order:
				// wrong data with no error. Alias one side instead.
				return p, fmt.Errorf("column %q appears more than once in the result and Order.Active cannot choose between them — alias one in the query", f.Name)
			}
			if f.TypeOID != postgres.OIDBool {
				return p, fmt.Errorf("column %q is OID %d, which Order.Active cannot hold", f.Name, f.TypeOID)
			}
			p.colActive = i
		case "created_at":
			if p.colCreatedAt >= 0 {
				// Two columns of this name in one result — an ordinary join
				// does it. Last-wins binding would pick one silently, and
				// which one is a property of the SELECT's column order:
				// wrong data with no error. Alias one side instead.
				return p, fmt.Errorf("column %q appears more than once in the result and Order.CreatedAt cannot choose between them — alias one in the query", f.Name)
			}
			if f.TypeOID != postgres.OIDTimestampTZ && f.TypeOID != postgres.OIDTimestamp {
				return p, fmt.Errorf("column %q is OID %d, which Order.CreatedAt cannot hold", f.Name, f.TypeOID)
			}
			p.colCreatedAt = i
		case "note":
			if p.colNote >= 0 {
				// Two columns of this name in one result — an ordinary join
				// does it. Last-wins binding would pick one silently, and
				// which one is a property of the SELECT's column order:
				// wrong data with no error. Alias one side instead.
				return p, fmt.Errorf("column %q appears more than once in the result and Order.Note cannot choose between them — alias one in the query", f.Name)
			}
			if f.TypeOID != postgres.OIDText && f.TypeOID != postgres.OIDVarchar && f.TypeOID != postgres.OIDBPChar && f.TypeOID != postgres.OIDName {
				return p, fmt.Errorf("column %q is OID %d, which Order.Note cannot hold", f.Name, f.TypeOID)
			}
			p.colNote = i
		}
	}
	if p.colID < 0 {
		return p, fmt.Errorf("the result has no column %q for Order.ID", "id")
	}
	if p.colTotal < 0 {
		return p, fmt.Errorf("the result has no column %q for Order.Total", "total_amount")
	}
	if p.colLabel < 0 {
		return p, fmt.Errorf("the result has no column %q for Order.Label", "label")
	}
	if p.colActive < 0 {
		return p, fmt.Errorf("the result has no column %q for Order.Active", "is_active")
	}
	if p.colCreatedAt < 0 {
		return p, fmt.Errorf("the result has no column %q for Order.CreatedAt", "created_at")
	}
	if p.colNote < 0 {
		return p, fmt.Errorf("the result has no column %q for Order.Note", "note")
	}
	return p, nil
}

// HydrateOrder appends one batch of rows to dst.
//
// The loop is row-major, which measurement chose over the columnar shape
// §8.6 originally specified: 31.2 ns/row against 34.7, and 26.3 against 37.6
// on a batch of one (measured, see docs/benchmarks.md).
// On an error dst is returned as it stood before this batch — capacity and
// prior contents intact — so a caller that logs and moves on keeps its reuse
// buffer rather than having it replaced by nil.
func HydrateOrder(dst []Order, rows *postgres.Rows, p OrderPlan) ([]Order, error) {
	before := len(dst)
	// Reserved up front with amortized growth: the batch's row count is
	// known, and slices.Grow both skips append's per-batch reallocation on a
	// fresh buffer and gives a buffer accumulating batch after batch the
	// headroom an exact-fit reservation would deny it.
	dst = slices.Grow(dst, rows.Len())
	for i := range rows.Len() {
		var e Order
		{
			b, isNull := rows.Value(i, p.colID)
			if isNull {
				return dst[:before], fmt.Errorf("row %d: column %q is NULL and Order.ID cannot hold it", i, "id")
			}
			v, err := postgres.DecodeInt8(b)
			if err != nil {
				return dst[:before], fmt.Errorf("row %d, column %q: %w", i, "id", err)
			}
			e.ID = v
		}
		{
			b, isNull := rows.Value(i, p.colTotal)
			if isNull {
				return dst[:before], fmt.Errorf("row %d: column %q is NULL and Order.Total cannot hold it", i, "total_amount")
			}
			v, err := postgres.DecodeFloat8(b)
			if err != nil {
				return dst[:before], fmt.Errorf("row %d, column %q: %w", i, "total_amount", err)
			}
			e.Total = v
		}
		{
			b, isNull := rows.Value(i, p.colLabel)
			if isNull {
				return dst[:before], fmt.Errorf("row %d: column %q is NULL and Order.Label cannot hold it", i, "label")
			}
			e.Label = string(b)
		}
		{
			b, isNull := rows.Value(i, p.colActive)
			if isNull {
				return dst[:before], fmt.Errorf("row %d: column %q is NULL and Order.Active cannot hold it", i, "is_active")
			}
			v, err := postgres.DecodeBool(b)
			if err != nil {
				return dst[:before], fmt.Errorf("row %d, column %q: %w", i, "is_active", err)
			}
			e.Active = v
		}
		{
			b, isNull := rows.Value(i, p.colCreatedAt)
			if isNull {
				return dst[:before], fmt.Errorf("row %d: column %q is NULL and Order.CreatedAt cannot hold it", i, "created_at")
			}
			v, err := postgres.DecodeTimestampTZ(b)
			if err != nil {
				return dst[:before], fmt.Errorf("row %d, column %q: %w", i, "created_at", err)
			}
			e.CreatedAt = v
		}
		{
			b, isNull := rows.Value(i, p.colNote)
			if !isNull {
				v := string(b)
				e.Note = &v
			}
		}
		dst = append(dst, e)
	}
	return dst, nil
}
