// Code generated by sluicegen (format 1). DO NOT EDIT.

package entity

import (
	"fmt"
	"slices"

	"github.com/mlagarrigue/sluice/database/postgres"
)

// ProductPlan binds Product's fields to the columns of one result.
//
// Binding happens once per result rather than once per row, and it is where
// two mistakes are caught that would otherwise be silent: a column that moved
// (columns are matched by name, never by position) and a column whose type
// changed under the entity.
type ProductPlan struct {
	colSKU       int
	colOwner     int
	colImage     int
	colThumbnail int
	colPrice     int
	colReleased  int
}

// BindProduct resolves the columns Product needs in the result described
// by fields.
func BindProduct(fields []postgres.Field) (ProductPlan, error) {
	var p ProductPlan
	p.colSKU = -1
	p.colOwner = -1
	p.colImage = -1
	p.colThumbnail = -1
	p.colPrice = -1
	p.colReleased = -1
	for i, f := range fields {
		switch f.Name {
		case "sku":
			if p.colSKU >= 0 {
				// Two columns of this name in one result — an ordinary join
				// does it. Last-wins binding would pick one silently, and
				// which one is a property of the SELECT's column order:
				// wrong data with no error. Alias one side instead.
				return p, fmt.Errorf("column %q appears more than once in the result and Product.SKU cannot choose between them — alias one in the query", f.Name)
			}
			if f.TypeOID != postgres.OIDText && f.TypeOID != postgres.OIDVarchar && f.TypeOID != postgres.OIDBPChar && f.TypeOID != postgres.OIDName {
				return p, fmt.Errorf("column %q is OID %d, which Product.SKU cannot hold", f.Name, f.TypeOID)
			}
			p.colSKU = i
		case "owner":
			if p.colOwner >= 0 {
				// Two columns of this name in one result — an ordinary join
				// does it. Last-wins binding would pick one silently, and
				// which one is a property of the SELECT's column order:
				// wrong data with no error. Alias one side instead.
				return p, fmt.Errorf("column %q appears more than once in the result and Product.Owner cannot choose between them — alias one in the query", f.Name)
			}
			if f.TypeOID != postgres.OIDText && f.TypeOID != postgres.OIDVarchar && f.TypeOID != postgres.OIDBPChar && f.TypeOID != postgres.OIDName {
				return p, fmt.Errorf("column %q is OID %d, which Product.Owner cannot hold", f.Name, f.TypeOID)
			}
			p.colOwner = i
		case "image":
			if p.colImage >= 0 {
				// Two columns of this name in one result — an ordinary join
				// does it. Last-wins binding would pick one silently, and
				// which one is a property of the SELECT's column order:
				// wrong data with no error. Alias one side instead.
				return p, fmt.Errorf("column %q appears more than once in the result and Product.Image cannot choose between them — alias one in the query", f.Name)
			}
			if f.TypeOID != postgres.OIDBytea {
				return p, fmt.Errorf("column %q is OID %d, which Product.Image cannot hold", f.Name, f.TypeOID)
			}
			p.colImage = i
		case "thumbnail":
			if p.colThumbnail >= 0 {
				// Two columns of this name in one result — an ordinary join
				// does it. Last-wins binding would pick one silently, and
				// which one is a property of the SELECT's column order:
				// wrong data with no error. Alias one side instead.
				return p, fmt.Errorf("column %q appears more than once in the result and Product.Thumbnail cannot choose between them — alias one in the query", f.Name)
			}
			if f.TypeOID != postgres.OIDBytea {
				return p, fmt.Errorf("column %q is OID %d, which Product.Thumbnail cannot hold", f.Name, f.TypeOID)
			}
			p.colThumbnail = i
		case "price":
			if p.colPrice >= 0 {
				// Two columns of this name in one result — an ordinary join
				// does it. Last-wins binding would pick one silently, and
				// which one is a property of the SELECT's column order:
				// wrong data with no error. Alias one side instead.
				return p, fmt.Errorf("column %q appears more than once in the result and Product.Price cannot choose between them — alias one in the query", f.Name)
			}
			if f.TypeOID != postgres.OIDNumeric {
				return p, fmt.Errorf("column %q is OID %d, which Product.Price cannot hold", f.Name, f.TypeOID)
			}
			p.colPrice = i
		case "released":
			if p.colReleased >= 0 {
				// Two columns of this name in one result — an ordinary join
				// does it. Last-wins binding would pick one silently, and
				// which one is a property of the SELECT's column order:
				// wrong data with no error. Alias one side instead.
				return p, fmt.Errorf("column %q appears more than once in the result and Product.Released cannot choose between them — alias one in the query", f.Name)
			}
			if f.TypeOID != postgres.OIDDate {
				return p, fmt.Errorf("column %q is OID %d, which Product.Released cannot hold", f.Name, f.TypeOID)
			}
			p.colReleased = i
		}
	}
	if p.colSKU < 0 {
		return p, fmt.Errorf("the result has no column %q for Product.SKU", "sku")
	}
	if p.colOwner < 0 {
		return p, fmt.Errorf("the result has no column %q for Product.Owner", "owner")
	}
	if p.colImage < 0 {
		return p, fmt.Errorf("the result has no column %q for Product.Image", "image")
	}
	if p.colThumbnail < 0 {
		return p, fmt.Errorf("the result has no column %q for Product.Thumbnail", "thumbnail")
	}
	if p.colPrice < 0 {
		return p, fmt.Errorf("the result has no column %q for Product.Price", "price")
	}
	if p.colReleased < 0 {
		return p, fmt.Errorf("the result has no column %q for Product.Released", "released")
	}
	return p, nil
}

// HydrateProduct appends one batch of rows to dst.
//
// The loop is row-major, which measurement chose over the columnar shape
// §8.6 originally specified: 31.2 ns/row against 34.7, and 26.3 against 37.6
// on a batch of one (measured, see docs/benchmarks.md).
// On an error dst is returned as it stood before this batch — capacity and
// prior contents intact — so a caller that logs and moves on keeps its reuse
// buffer rather than having it replaced by nil.
func HydrateProduct(dst []Product, rows *postgres.Rows, p ProductPlan) ([]Product, error) {
	before := len(dst)
	// Reserved up front with amortized growth: the batch's row count is
	// known, and slices.Grow both skips append's per-batch reallocation on a
	// fresh buffer and gives a buffer accumulating batch after batch the
	// headroom an exact-fit reservation would deny it.
	dst = slices.Grow(dst, rows.Len())
	for i := range rows.Len() {
		var e Product
		{
			b, isNull := rows.Value(i, p.colSKU)
			if isNull {
				return dst[:before], fmt.Errorf("row %d: column %q is NULL and Product.SKU cannot hold it", i, "sku")
			}
			e.SKU = string(b)
		}
		{
			b, isNull := rows.Value(i, p.colOwner)
			if isNull {
				return dst[:before], fmt.Errorf("row %d: column %q is NULL and Product.Owner cannot hold it", i, "owner")
			}
			e.Owner = string(b)
		}
		{
			b, isNull := rows.Value(i, p.colImage)
			if isNull {
				return dst[:before], fmt.Errorf("row %d: column %q is NULL and Product.Image cannot hold it", i, "image")
			}
			e.Image = slices.Clone(b)
		}
		{
			b, isNull := rows.Value(i, p.colThumbnail)
			if !isNull {
				v := slices.Clone(b)
				e.Thumbnail = &v
			}
		}
		{
			b, isNull := rows.Value(i, p.colPrice)
			if isNull {
				return dst[:before], fmt.Errorf("row %d: column %q is NULL and Product.Price cannot hold it", i, "price")
			}
			v, err := postgres.DecodeNumeric(b)
			if err != nil {
				return dst[:before], fmt.Errorf("row %d, column %q: %w", i, "price", err)
			}
			e.Price = v
		}
		{
			b, isNull := rows.Value(i, p.colReleased)
			if isNull {
				return dst[:before], fmt.Errorf("row %d: column %q is NULL and Product.Released cannot hold it", i, "released")
			}
			v, err := postgres.DecodeDate(b)
			if err != nil {
				return dst[:before], fmt.Errorf("row %d, column %q: %w", i, "released", err)
			}
			e.Released = v
		}
		dst = append(dst, e)
	}
	return dst, nil
}
